### ISSUE TITLE
BUG: mozjs60 can't be built

### ISSUE THREAD

**Issue by protonesso** [ataraxialinux/ataraxia#54]
## Specifications

  - Architecture: all
  - Package Version: 60.6.1

Other Notes:
Build log:
```
Traceback (most recent call last):
  File "./../../configure.py", line 127, in <module>
    sys.exit(main(sys.argv))
  File "./../../configure.py", line 34, in main
    return config_status(config)
  File "./../../configure.py", line 122, in config_status
    return config_status(args=[], **encode(sanitized_config, encoding))
  File "/var/cache/ports/packages/mozjs60/work/src/firefox-60.6.1/python/mozbuild/mozbuild/config_status.py", line 144, in config_status
    definitions = list(definitions)
  File "/var/cache/ports/packages/mozjs60/work/src/firefox-60.6.1/python/mozbuild/mozbuild/frontend/emitter.py", line 184, in emit
    objs = list(emitfn(out))
  File "/var/cache/ports/packages/mozjs60/work/src/firefox-60.6.1/python/mozbuild/mozbuild/frontend/emitter.py", line 1134, in emit_from_context
    full_path), context)
mozbuild.frontend.reader.SandboxValidationError: 
==============================
FATAL ERROR PROCESSING MOZBUILD FILE
==============================

The error occurred while processing the following file or one of the files it includes:

    /var/cache/ports/packages/mozjs60/work/src/firefox-60.6.1/js/src/shell/moz.build

The error occurred when validating the result of the execution. The reported error is:

    Path specified in LOCAL_INCLUDES is not allowed: .. (resolved to /var/cache/ports/packages/mozjs60/work/src/firefox-60.6.1/js/src)


=======> ERROR: Building '/var/cache/packages/mozjs60#60.6.1-1.pkg.tar.lz4' failed.
```

**Comment by awilfox** [comment]
I didn't see the mozjs60 package in the Git repository, so I don't know if this was fixed or not.  If it isn't: we ran in to this at @AdelieLinux.  The issue is that you must configure and build out-of-tree.  For instance, `mkdir build; cd build; ../configure`.

**Comment by protonesso** [comment]
Thanks
